# Generated by Django 3.2 on 2022-02-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_alter_assignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
